2018-07-31 18:00:50,206 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:69]
2018-08-06 19:27:59,508 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-06 19:45:03,205 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-06 19:45:36,801 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:02:19,852 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:02:47,523 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:44:19,776 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:44:38,221 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:50:46,592 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:51:07,684 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 01:51:20,887 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 13:47:16,080 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 13:49:21,965 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 13:52:24,009 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 13:52:41,903 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 14:27:38,589 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 14:28:36,446 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 14:55:10,448 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 14:56:43,049 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 14:58:38,379 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 15:00:20,615 INFO: Ridemyway startup [in /home/kiptoo/Desktop/repos/Ridemyway/app/__init__.py:79]
2018-08-07 15:00:59,437 ERROR: Exception on /dashboard [GET] [in /home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py", line 2082, in _determine_joins
    consider_as_foreign_keys=consider_as_foreign_keys
  File "<string>", line 2, in join_condition
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/sql/selectable.py", line 968, in _join_condition
    a, b, constraints, consider_as_foreign_keys)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/sql/selectable.py", line 1058, in _joincond_trim_constraints
    "join explicitly." % (a.description, b.description))
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'user' and 'request'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/kiptoo/Desktop/repos/Ridemyway/app/main/routes.py", line 11, in before_request
    if current_user.is_authenticated:
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/home/kiptoo/Desktop/repos/Ridemyway/app/models.py", line 163, in load_user
    return User.query.get(int(id))
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 1272, in _configure_all
    configure_mappers()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 3029, in configure_mappers
    mapper._post_configure_properties()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 1828, in _post_configure_properties
    prop.init()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/interfaces.py", line 183, in init
    self.do_init()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py", line 1656, in do_init
    self._setup_join_conditions()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py", line 1731, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py", line 1998, in __init__
    self._determine_joins()
  File "/home/kiptoo/Desktop/repos/Ridemyway/venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py", line 2126, in _determine_joins
    % self.prop)
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.requests - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.
